# Week 1
## Timo Ijäs
## Introduction to data science

In [21]:
import pandas as pd
import geopandas as gpd
import numpy as np
import time

### Exercise 1

In [22]:
# initialize arrays

a = list(range(0,1000000))
b = a

# print for testing

print(len(a))
print(a[:10])
print(len(b))
print(b[:10])

1000000
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1000000
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [23]:
 # make function
    
def add_with_for(a, b):
     c = []
     for i in range(len(a)):
        c.append(a[i] + b[i])
     return c


In [24]:
# test function
start_time = time.perf_counter()
d = add_with_for(a,b)
elapsed_time = time.perf_counter() - start_time

print('Time elapsed: ' + str(elapsed_time) + ' seconds')
print(d[5:50])

Time elapsed: 0.24731099999999984 seconds
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [25]:
# Try summing arrays
e = a + b
print(e[:50])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


Summing simple arrays doesn't work.

In [26]:
# Same with numpy
numA = np.array(range(0,10000000))
numB = numA



In [27]:
print(type(numA))
print(type(numB))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [28]:
def add_with_sum(numA,numB):
    numC = numA + numB
    return numC

In [29]:
start_time = time.perf_counter()
numC = add_with_sum(numA,numB)
elapsed_time = time.perf_counter() - start_time

print('Time elapsed: ' + str(elapsed_time) + ' seconds')
print(numC[:10])

Time elapsed: 0.04916060000000044 seconds
[ 0  2  4  6  8 10 12 14 16 18]


In [30]:
def add_with_np_add(numA,numB):
    numD = np.add(numA,numB)
    return numD

In [31]:
start_time = time.perf_counter()

numD = add_with_np_add(numA,numB)
elapsed_time = time.perf_counter() - start_time

print('Time elapsed: ' + str(elapsed_time) + ' seconds')
print(numD[0:10])

Time elapsed: 0.04060300000000083 seconds
[ 0  2  4  6  8 10 12 14 16 18]


Using numpy arrays is faster and can be for any arrays as long as they are the same shape. Even if they're not just simple on dimensional arrays. And they can be added by simply using a + b.


### Array Manipulation
#### a)

In [32]:
a = np.arange(100).reshape((10, 10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### b)

In [33]:
a = np.zeros(50)
print(a)
b = np.ones(50)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [34]:
c = np.dstack((a,b))
c= c.reshape(10,10)
c

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

#### c)

In [35]:
# create array of 10 x -1
a = np.zeros(10)
a = a - 1
a

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [36]:
# make diagonal of -1 and add 1 to each element
b = np.diag(a)
b = b +1
b

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

#### d)

In [37]:
# Flip the table
c= np.fliplr(b)
c


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### e) 
det(CD) and det(C) * det(D), and show that they are the same. Why does this hold in this instance? Does it hold in general?

In [38]:
dotBC = b.dot(c)
detA = np.linalg.det(dotBC)
detA

-81.00000000000003

In [39]:
detB = np.linalg.det(b)
detC = np.linalg.det(c) 
detBdetC = detB * detC
detBdetC

-81.0

-> det(BC) = det(B) * det(C)

##### Why does it hold? Does it hold in other instances?
It is a general rule that the determinant of two matrices product and the product of their determinants is the same. Therefore the rule holds in all instances.


###  Slicing

#### a)

In [44]:
from sklearn import datasets
dataset = sklearn.datasets.load_boston()


df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df['target'] = dataset.target
print(df.shape)
df.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [45]:
dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [46]:
X = dataset['data']
y = dataset['feature_names']
print(X.shape)
print(y.shape)

(506, 13)
(13,)


In [47]:
ds = np.vstack((y, X)).T
ds.shape


(13, 507)

In [48]:
ds2 = X.T
ds2.shape
ds2[0,:10]

array([0.00632, 0.02731, 0.02729, 0.03237, 0.06905, 0.02985, 0.08829,
       0.14455, 0.21124, 0.17004])

#### b) crime 'CRIM' is higher than 1

In [49]:
rows = np.where(X[:,0] >1)
result = X[rows]
result

array([[  1.05393,   0.     ,   8.14   , ...,  21.     , 386.85   ,
          6.58   ],
       [  1.25179,   0.     ,   8.14   , ...,  21.     , 376.57   ,
         21.02   ],
       [  1.23247,   0.     ,   8.14   , ...,  21.     , 396.9    ,
         18.72   ],
       ...,
       [  3.67367,   0.     ,  18.1    , ...,  20.2    , 388.62   ,
         10.58   ],
       [  5.69175,   0.     ,  18.1    , ...,  20.2    , 392.68   ,
         14.98   ],
       [  4.83567,   0.     ,  18.1    , ...,  20.2    , 388.22   ,
         11.45   ]])

In [50]:
rows

(array([ 16,  20,  22,  29,  30,  31,  32,  33,  34, 131, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 310, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
        366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378,
        379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391,
        392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404,
        405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417,
        418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430,
        431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443,
        444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456,
        457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469,
        470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482,
        483, 484, 485, 486, 487], dtype=int64),)

#### c) Select the rows where the pupil-to-teach ratio is between 16% and 18% (exclusive). 

In [51]:
y

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [52]:
# Find index of ptratio
ptrI = np.where(y =='PTRATIO')
ptrI

(array([10], dtype=int64),)

In [53]:
rowsB = np.where((X[:,10] >16) & (X[:,10] <18))
resultB = X[ptrI]
print(resultB.shape)
print(resultB)

(1, 13)
[[2.2489e-01 1.2500e+01 7.8700e+00 0.0000e+00 5.2400e-01 6.3770e+00
  9.4300e+01 6.3467e+00 5.0000e+00 3.1100e+02 1.5200e+01 3.9252e+02
  2.0450e+01]]


#### d) mean nitric oxides for houses over 25

In [54]:
prices = dataset['target']
priceI = np.where(prices >25)
houses = X[priceI]
nox = houses[:,4]

print(nox)
print(type(nox))

[0.469  0.458  0.458  0.458  0.524  0.428  0.428  0.448  0.448  0.403
 0.411  0.4161 0.426  0.449  0.489  0.445  0.445  0.445  0.445  0.52
 0.52   0.605  0.605  0.605  0.605  0.605  0.605  0.51   0.51   0.488
 0.488  0.488  0.488  0.488  0.488  0.488  0.488  0.437  0.437  0.437
 0.437  0.437  0.437  0.401  0.401  0.422  0.404  0.404  0.404  0.403
 0.403  0.415  0.4161 0.4161 0.489  0.55   0.507  0.507  0.507  0.504
 0.504  0.504  0.504  0.504  0.504  0.504  0.507  0.507  0.507  0.507
 0.507  0.431  0.431  0.431  0.394  0.647  0.647  0.647  0.647  0.647
 0.647  0.647  0.647  0.647  0.575  0.575  0.464  0.464  0.447  0.447
 0.447  0.447  0.447  0.4429 0.4429 0.4429 0.4429 0.401  0.4    0.411
 0.411  0.411  0.437  0.437  0.4    0.433  0.433  0.472  0.472  0.472
 0.472  0.442  0.484  0.429  0.41   0.718  0.631  0.631  0.631  0.631
 0.668  0.659  0.597  0.614 ]
<class 'numpy.ndarray'>


In [55]:
noxmean = np.mean(nox)
print(noxmean)

0.4921201612903226


## Exercise 2

#### a) read json

In [102]:
import json
def load_tester(path):
    with open(path) as f:
        data = json.load(f)
    return np.asarray(data)

fpath = "Automotive_5.json"

In [57]:
dataj = pd.read_json('Automotive_5.json', lines=True)
print(dataj.columns)
dataj

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime'],
      dtype='object')


reviewerID        asin                        reviewerName  \
0      A3F73SC1LY51OO  B00002243X                     Alan Montgomery   
1      A20S66SKYXULG2  B00002243X                            alphonse   
2      A2I8LFSN2IS5EO  B00002243X                               Chris   
3      A3GT2EWQSO45ZG  B00002243X                              DeusEx   
4      A3ESWJPAVRPWB4  B00002243X                        E. Hernandez   
...               ...         ...                                 ...   
20468  A1KB43BI085A48  B00KIAQ8VW                             Mike F.   
20469  A3HIUWKL4D853W  B00KIAQ8VW                                RayH   
20470  A1S95WASXJ02VX  B00KIAQ8VW                 Roberto Aguilar Jr.   
20471  A2IID0Z6EHF5KP  B00KIAQ8VW                              Soarer   
20472  A3HKZTFCPIK2OE  B00KIAQ8VW  SSG Barnes (ABN) "James C. Barnes"   

        helpful                                         reviewText  overall  \
0        [4, 4]  I needed a set of jumper cables for my new car...        5   
1        [1, 1]  These long cables work fine for my truck, but ...        4   
2        [0, 0]  Can't comment much on these since they have no...        5   
3      [19, 19]  I absolutley love Amazon!!!  For the price of ...        5   
4        [0, 0]  I purchased the 12' feet long cable set and th...        5   
...         ...                                                ...      ...   
20468    [1, 1]  I've bought 10 of these over the past year to ...        5   
20469    [0, 0]  OK, I have to admit, the price of this item di...        2   
20470    [0, 0]  I love my skull face mask. It makes me outstan...        5   
20471    [0, 0]  This mask of course as described is half-face ...        5   
20472    [0, 0]  Good light weight for just cool nights or rain...        5   

                                                 summary  unixReviewTime  \
0             Work Well - Should Have Bought Longer Ones      1313539200   
1                                       Okay long cables      1315094400   
2                             Looks and feels heavy Duty      1374710400   
3                  Excellent choice for Jumper Cables!!!      1292889600   
4                 Excellent, High Quality Starter Cables      1341360000   
...                                                  ...             ...   
20468                    Excellent quality for the price      1396915200   
20469  Light weight neck and face cover with whimsica...      1391472000   
20470            I love to ride with my Skull Face Mask.      1386547200   
20471                              Great neck protection      1357171200   
20472                                          FACE MASK      1395100800   

        reviewTime  
0      08 17, 2011  
1       09 4, 2011  
2      07 25, 2013  
3      12 21, 2010  
4       07 4, 2012  
...            ...  
20468   04 8, 2014  
20469   02 4, 2014  
20470   12 9, 2013  
20471   01 3, 2013  
20472  03 18, 2014  

[20473 rows x 9 columns]

#### b) downcase the text

In [58]:
dataj['reviewText'] = dataj['reviewText'].str.lower()
dataj

reviewerID        asin                        reviewerName  \
0      A3F73SC1LY51OO  B00002243X                     Alan Montgomery   
1      A20S66SKYXULG2  B00002243X                            alphonse   
2      A2I8LFSN2IS5EO  B00002243X                               Chris   
3      A3GT2EWQSO45ZG  B00002243X                              DeusEx   
4      A3ESWJPAVRPWB4  B00002243X                        E. Hernandez   
...               ...         ...                                 ...   
20468  A1KB43BI085A48  B00KIAQ8VW                             Mike F.   
20469  A3HIUWKL4D853W  B00KIAQ8VW                                RayH   
20470  A1S95WASXJ02VX  B00KIAQ8VW                 Roberto Aguilar Jr.   
20471  A2IID0Z6EHF5KP  B00KIAQ8VW                              Soarer   
20472  A3HKZTFCPIK2OE  B00KIAQ8VW  SSG Barnes (ABN) "James C. Barnes"   

        helpful                                         reviewText  overall  \
0        [4, 4]  i needed a set of jumper cables for my new car...        5   
1        [1, 1]  these long cables work fine for my truck, but ...        4   
2        [0, 0]  can't comment much on these since they have no...        5   
3      [19, 19]  i absolutley love amazon!!!  for the price of ...        5   
4        [0, 0]  i purchased the 12' feet long cable set and th...        5   
...         ...                                                ...      ...   
20468    [1, 1]  i've bought 10 of these over the past year to ...        5   
20469    [0, 0]  ok, i have to admit, the price of this item di...        2   
20470    [0, 0]  i love my skull face mask. it makes me outstan...        5   
20471    [0, 0]  this mask of course as described is half-face ...        5   
20472    [0, 0]  good light weight for just cool nights or rain...        5   

                                                 summary  unixReviewTime  \
0             Work Well - Should Have Bought Longer Ones      1313539200   
1                                       Okay long cables      1315094400   
2                             Looks and feels heavy Duty      1374710400   
3                  Excellent choice for Jumper Cables!!!      1292889600   
4                 Excellent, High Quality Starter Cables      1341360000   
...                                                  ...             ...   
20468                    Excellent quality for the price      1396915200   
20469  Light weight neck and face cover with whimsica...      1391472000   
20470            I love to ride with my Skull Face Mask.      1386547200   
20471                              Great neck protection      1357171200   
20472                                          FACE MASK      1395100800   

        reviewTime  
0      08 17, 2011  
1       09 4, 2011  
2      07 25, 2013  
3      12 21, 2010  
4       07 4, 2012  
...            ...  
20468   04 8, 2014  
20469   02 4, 2014  
20470   12 9, 2013  
20471   01 3, 2013  
20472  03 18, 2014  

[20473 rows x 9 columns]

#### c) remove punctuation and stopwords

In [59]:
import string
dataj['reviewText']= dataj['reviewText'].str.replace('[{}]'.format(string.punctuation),'')
dataj

reviewerID        asin                        reviewerName  \
0      A3F73SC1LY51OO  B00002243X                     Alan Montgomery   
1      A20S66SKYXULG2  B00002243X                            alphonse   
2      A2I8LFSN2IS5EO  B00002243X                               Chris   
3      A3GT2EWQSO45ZG  B00002243X                              DeusEx   
4      A3ESWJPAVRPWB4  B00002243X                        E. Hernandez   
...               ...         ...                                 ...   
20468  A1KB43BI085A48  B00KIAQ8VW                             Mike F.   
20469  A3HIUWKL4D853W  B00KIAQ8VW                                RayH   
20470  A1S95WASXJ02VX  B00KIAQ8VW                 Roberto Aguilar Jr.   
20471  A2IID0Z6EHF5KP  B00KIAQ8VW                              Soarer   
20472  A3HKZTFCPIK2OE  B00KIAQ8VW  SSG Barnes (ABN) "James C. Barnes"   

        helpful                                         reviewText  overall  \
0        [4, 4]  i needed a set of jumper cables for my new car...        5   
1        [1, 1]  these long cables work fine for my truck but t...        4   
2        [0, 0]  cant comment much on these since they have not...        5   
3      [19, 19]  i absolutley love amazon  for the price of a s...        5   
4        [0, 0]  i purchased the 12 feet long cable set and the...        5   
...         ...                                                ...      ...   
20468    [1, 1]  ive bought 10 of these over the past year to g...        5   
20469    [0, 0]  ok i have to admit the price of this item did ...        2   
20470    [0, 0]  i love my skull face mask it makes me outstand...        5   
20471    [0, 0]  this mask of course as described is halfface b...        5   
20472    [0, 0]  good light weight for just cool nights or rain...        5   

                                                 summary  unixReviewTime  \
0             Work Well - Should Have Bought Longer Ones      1313539200   
1                                       Okay long cables      1315094400   
2                             Looks and feels heavy Duty      1374710400   
3                  Excellent choice for Jumper Cables!!!      1292889600   
4                 Excellent, High Quality Starter Cables      1341360000   
...                                                  ...             ...   
20468                    Excellent quality for the price      1396915200   
20469  Light weight neck and face cover with whimsica...      1391472000   
20470            I love to ride with my Skull Face Mask.      1386547200   
20471                              Great neck protection      1357171200   
20472                                          FACE MASK      1395100800   

        reviewTime  
0      08 17, 2011  
1       09 4, 2011  
2      07 25, 2013  
3      12 21, 2010  
4       07 4, 2012  
...            ...  
20468   04 8, 2014  
20469   02 4, 2014  
20470   12 9, 2013  
20471   01 3, 2013  
20472  03 18, 2014  

[20473 rows x 9 columns]

In [103]:
stops = pd.read_csv('stop-word-list.csv', header = None)

import csv 
with open('stop-word-list.csv', newline='') as f:
    reader = csv.reader(f)
    for row in reader:
        stopwords = row
stopwords = list(map(str.strip, stopwords))

dataj.reviewText = dataj.reviewText.str.replace(f'\\b({"|".join(stopwords)})\\b','')
dataj

reviewerID        asin                        reviewerName  \
0      A3F73SC1LY51OO  B00002243X                     Alan Montgomery   
1      A20S66SKYXULG2  B00002243X                            alphonse   
2      A2I8LFSN2IS5EO  B00002243X                               Chris   
3      A3GT2EWQSO45ZG  B00002243X                              DeusEx   
4      A3ESWJPAVRPWB4  B00002243X                        E. Hernandez   
...               ...         ...                                 ...   
20468  A1KB43BI085A48  B00KIAQ8VW                             Mike F.   
20469  A3HIUWKL4D853W  B00KIAQ8VW                                RayH   
20470  A1S95WASXJ02VX  B00KIAQ8VW                 Roberto Aguilar Jr.   
20471  A2IID0Z6EHF5KP  B00KIAQ8VW                              Soarer   
20472  A3HKZTFCPIK2OE  B00KIAQ8VW  SSG Barnes (ABN) "James C. Barnes"   

        helpful                                         reviewText  overall  \
0        [4, 4]  need set jumper cabl new car good review good ...        5   
1        [1, 1]  long cabl work fine truck qualiti seem littl s...        4   
2        [0, 0]  cant comment much use come back updat review f...        5   
3      [19, 19]  absolutley love amazon price set cheap booster...        5   
4        [0, 0]  purchas 12 feet long cabl set arriv retail car...        5   
...         ...                                                ...      ...   
20468    [1, 1]  ive bought 10 over past year give gift friend ...        5   
20469    [0, 0]  ok admit price item expect unfairli high strai...        2   
20470    [0, 0]  love skull face mask make outstand rest fellow...        5   
20471    [0, 0]  mask cours describ halffac long protect neck g...        5   
20472    [0, 0]  good light weight cool night rain half helmet ...        5   

                                                 summary  unixReviewTime  \
0             Work Well - Should Have Bought Longer Ones      1313539200   
1                                       Okay long cables      1315094400   
2                             Looks and feels heavy Duty      1374710400   
3                  Excellent choice for Jumper Cables!!!      1292889600   
4                 Excellent, High Quality Starter Cables      1341360000   
...                                                  ...             ...   
20468                    Excellent quality for the price      1396915200   
20469  Light weight neck and face cover with whimsica...      1391472000   
20470            I love to ride with my Skull Face Mask.      1386547200   
20471                              Great neck protection      1357171200   
20472                                          FACE MASK      1395100800   

        reviewTime  
0      08 17, 2011  
1       09 4, 2011  
2      07 25, 2013  
3      12 21, 2010  
4       07 4, 2012  
...            ...  
20468   04 8, 2014  
20469   02 4, 2014  
20470   12 9, 2013  
20471   01 3, 2013  
20472  03 18, 2014  

[20473 rows x 9 columns]

#### d) Apply stemmer

In [105]:
from nltk.stem.porter import *
stemmer = PorterStemmer()

splitdf = dataj['reviewText'].str.split()
dataj['reviewText'][0].str.split()

AttributeError: 'str' object has no attribute 'str'

In [106]:
stemmed = splitdf.apply(lambda x: [stemmer.stem(y) for y in x])
stemmed

0        [need, set, jumper, cabl, new, car, good, revi...
1        [long, cabl, work, fine, truck, qualiti, seem,...
2        [cant, comment, much, use, come, back, updat, ...
3        [absolutley, love, amazon, price, set, cheap, ...
4        [purcha, 12, feet, long, cabl, set, arriv, ret...
                               ...                        
20468    [ive, bought, 10, over, past, year, give, gift...
20469    [ok, admit, price, item, expect, unfairli, hig...
20470    [love, skull, face, mask, make, outstand, rest...
20471    [mask, cour, describ, halffac, long, protect, ...
20472    [good, light, weight, cool, night, rain, half,...
Name: reviewText, Length: 20473, dtype: object

In [107]:
listToStr = stemmed.apply(lambda x: ' '.join([str(i) for i in x]))
listToStr

0        need set jumper cabl new car good review good ...
1        long cabl work fine truck qualiti seem littl s...
2        cant comment much use come back updat review f...
3        absolutley love amazon price set cheap booster...
4        purcha 12 feet long cabl set arriv retail card...
                               ...                        
20468    ive bought 10 over past year give gift friend ...
20469    ok admit price item expect unfairli high strai...
20470    love skull face mask make outstand rest fellow...
20471    mask cour describ halffac long protect neck gr...
20472    good light weight cool night rain half helmet ...
Name: reviewText, Length: 20473, dtype: object

In [108]:
dataj['reviewText'] = listToStr

In [88]:
goods = dataj.loc[(dataj['overall'] == 4) | (dataj['overall']==5)]
goodRev = goods['reviewText']

bads = dataj.loc[(dataj['overall'] == 2) | (dataj['overall']==1)]
badRev = bads['reviewText']


In [95]:
goodRev.to_csv('pos.txt', header= False, mode='w', index = None)
badRev.to_csv('neg.txt', header= False, mode='w', index = None)
